//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteManagementSystemDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public decimal Fees { get; set; }
        public string Description { get; set; }
        public int FacultyId { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public Nullable<System.DateTime> CourseEndDate { get; set; }
        public bool IsActive { get; set; }
        public int NoOfSeats { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
    
        public virtual FAcultyUser FAcultyUser { get; set; }
    }
}
