//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteManagementSystemDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAcultyUser
    {
        public FAcultyUser()
        {
            this.Courses = new HashSet<Cours>();
        }
    
        public int FacultyUsersId { get; set; }
        public string UserId { get; set; }
        public string Experience { get; set; }
        public string Achievements { get; set; }
        public Nullable<bool> Acitve { get; set; }
    
        public virtual ICollection<Cours> Courses { get; set; }
    }
}
